version: "2"
sql:
  - engine: "postgresql"
    queries: "../pkg/sqlc/"
    schema: "../migrations/"
    gen:
      go:
        package: "sqlc"
        out: "../pkg/sqlc/generate"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_prepared_queries: false
        emit_interface: false
        emit_empty_slices: true
        emit_exact_table_names: false